### ISSUE TITLE
URL should work at any position (not only at the end)

### ISSUE THREAD

**Issue by mittsh** [luckymarmot/Paw-cURLImporter#1]
All these work in curl and should work in this importer:

```
curl http://httpbin.org/basic-auth/user/passwd -I -H "X-My-Header: value"
curl -I http://httpbin.org/basic-auth/user/passwd -H "X-My-Header: value"
curl -I -H "X-My-Header: value" http://httpbin.org/basic-auth/user/passwd
```

**Comment by mittsh** [comment]
@hishnash this still doesn't work
`curl -I http://httpbin.org/basic-auth/user/passwd -H "X-My-Header: value"`

but probably fine for now, why don't we use a real argument parser?

**Comment by hishnash** [comment]
acroding the the man page:
http://curl.haxx.se/docs/manpage.html

that should not work.

To write a full passer we need it to unserstand all the options of curl. even through 80% of them are not relevent to paw.

**Comment by mittsh** [comment]
yes, that's right also...ok let's hope it works in most cases :) closing for now!
