### ISSUE TITLE
Breaks with --compressed

### ISSUE THREAD

**Issue by ccg** [luckymarmot/Paw-cURLImporter#10]
Try to import `curl 'https://www.google.com/' --compressed`, and you will get this error:

`TypeError: undefined is not a function (evaluating 'acceptEncoding.includes('gzip')')`

Try to import `curl 'https://www.google.com/'`, and it works.

The main problem (for me, at least) is that if copy a cURL out of Chrome Dev Tools, it puts `--compressed` on it.

**Comment by mittsh** [comment]
@ccg I'm not sure about the issue you're having… I have tested this exact string myself, and it works alright: http://cl.ly/2z3f3J411w1a

On which OS X version are you? I suspect the JavaScript version (more or less bound to the version of Safari the OS has) you're running is slightly different than the one I have, and a different OS version would explain a lot. I'm on the latest El Capitan _10.11.3 (15D21)_

**Comment by ccg** [comment]
Good point, I'm still on 10.10.5.

**Comment by mittsh** [comment]
@ccg thanks! I'll have a run on 10.10.5 to see…

**Comment by mittsh** [comment]
I finally debugged that, sorry for late! This is because `string.includes()` isn't available on OS X 10.10...I'll ship a fix for that!

**Comment by mittsh** [comment]
It's all fixed @ccg! You can update the extension by picking Paw menu > Extensions > Check for extensions updates

**Comment by ccg** [comment]
Confirmed, it's working well. Thank you for such a quick fix!
