### ISSUE TITLE
Tokenize & parse

### ISSUE THREAD

**Issue by mittsh** [luckymarmot/Paw-cURLImporter#3]
We probably should do it in multiple steps:
1. tokenzie the shell command (a good regexp is `((?:(?:\"(?:\\\"|[^\"])*?\")|(?:\'(?:\\\'|[^\'])*?\')|\S)+)`)
2. resolve quotes from tokens (part of the tokenizing process)
3. cleanup shell mess (e.g. redirection `|`, `>`, `1>`, `2>`, `2>&1`) -> maybe integrate this in the argument parser (step 4)
4. parse cURL arguments

note: read everything from the `curl` token, and ignore everything before, so we ignore shell prompt tokens like `$` or `>`

**Comment by mittsh** [comment]
Handle file inputs:
- `cat file | curl ...`
- `curl ... < file`
- ...

**Comment by hishnash** [comment]
For this we need some kind of depancy graph for eacy common bach comand

So we can do things like

curl httpbin.com/get | grep .... | curl

**Comment by mittsh** [comment]
Todo:
- [x] File refs in multipart `-F`, `--form`
- [x] Ignore tokens after consuming unknown options
- [x] Parse JSON `-d` strings correctly, to JSON body in Paw
- [x] Parse `--form-string` option
- [x] Parse `-m`, `--max-time`
- [x] Handle `--url`
- [ ] ~~Maybe parse `--proto-default`~~
- [x] `>` etc. consume one token for the filename, but next ones are still used by curl
- [x] `-x` options (with only one `-`) may have no space and the option is the rest of the characters (e.g. `-XPOST` works)

**Comment by mittsh** [comment]
@hishnash for now, I just split after a separator like this...

btw, now we can import fun stuff like that: `curl http://httpbin.org/get --data $'toto\ntiti' --data-binary @myfile.txt --data-raw @myfile.txt --data-ascii @myfile.txt -d @myfile.txt -d name=Paw -d key2=value2 -H Content-Type:text/plain`

![image](https://cloud.githubusercontent.com/assets/1319906/11915379/a39b8bbc-a6a4-11e5-9d81-460306927e93.png)

**Comment by hishnash** [comment]
we need to check the expected behavor if you use all the option.

**Comment by mittsh** [comment]
Yes, all tests and options I have were tested with the `curl` command line :)
